### PR TITLE
NXBT-1737: fix jdk8 download URL

### PR DESCRIPTION
**Pull request by atchertchian**

### CODE REVIEW

**Comment by nxmatic** [comment]
:+1: it rocks, updating also nuxeo-tools-docker according to.

**Comment by efge** [comment]
👍 hoping the random-looking string doesn't change every day or something like that.

**Comment by jcarsique** [comment]
How was it generated? Is it a random temporary token? Will another user following the same procedure get the same URL?
The fix must be sustainable else it's worth to use another solution.

:-1: After digging, this seems promised to recurrent failure:

> Unfortunately we have to require license acceptance prior to download. This can be implemented in one of two ways. Either we require registration and log in prior to download, and as part of registering you agree to reading and complying with licenses. Or we use a click-through on download which avoids the need to register and log in. We have chosen the latter for Java downloads as the least intrusive method. We found out some time ago that scripts were being used to circumvent click-through (in violation of site policies, and frankly also of common sense) and have plugged this hole.
>
> We understand that this makes command line updates from our main website for Linux users impossible and are actively looking for other ways to enable this use case.
>
> Oracle JDK is based on OpenJDK (with a few added components like a closed-source font rasterizer that we license from a third party) and the latter is available as part of most Linux distributions, so it is a good option unless you specifically need the Oracle certified binaries.
>
> Regards,
>
> Henrik Ståhl
> Sr. Director, Product Management
> Java Platform Group
> Oracle

**Comment by atchertchian** [comment]
The URL comes from the one visible on their download site at http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html
This is only a quick fix, feel free to do further changes to improve this and make it more maintainable, i just wanted the nightly demo to show current status, not the one from 10 days ago. Thanks!

**Comment by jcarsique** [comment]
Confirmed that it won't work. If you redo the procedure with a cleaned session, you get http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.tar.gz
It is a server-side temporary token.

**Pull request merged**
